name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest  # Рекомендуется использовать Linux для Python проектов

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4  # Исправлено на правильное действие
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=memory_cards --cov-report=term-missing --cov-report=xml --cov-report=html card_test.py -v --tb=short

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml  # Путь к файлу отчета о покрытии (если вы используете xml)

      - name: Notify on success or failure
        if: ${{ failure() }}
        run: echo "Tests failed!"  # Здесь можно добавить более сложные уведомления, например, через Slack или Email.