name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/checkout@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov PyQt5 pytest-mock
      - name: Run tests with coverage
        run: |
          pytest --cov=memory_cards --cov-report term-missing card_test.py -v --tb=short
      - name: Run tests with coverage
        run: |
          pytest --cov=memory_cards --cov-report term-missing card_test.py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true